name: CI/CD Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the jobs to run
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Specify your Node.js version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test

    # Build the application
    - name: Build application
      run: npm run build

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      run: |
        echo "Deploying application to production server"
        # Add your deployment commands here (e.g., SSH to your server and deploy the app)
